### ISSUE TITLE
Mac app doesn't load window after application start. 

### ISSUE THREAD

**Issue by levibostian** [ChangJoo-Park/gitrelease-app#1]
I went to the releases, downloaded v0.1, put into Applications folder and opened app (named electron-quick-start). 

No window opens, program does not show up in dock, however, process for electron-quick-start shows up in Activity Monitor. 

Expected behavior: Program opens, window appears for me to use. (and rename app to something other than electron-quick-start 😄). 

Great program! I am going to find this really handy! Can't wait to use.

**Comment by ChangJoo-Park** [comment]
@levibostian,  I forget to say it is tray app :)  Please check Menubar! octocat smile to you!

+ *Rename* is important thing. Thank you :)

**Comment by ChangJoo-Park** [comment]
check [this](https://github.com/ChangJoo-Park/gitrelease-app/releases/tag/0.1.1)
Please tell me when you find a problem or additional features!

**Comment by levibostian** [comment]
Awesome. The rename is nice, thanks. 

Is it possible when the app is first loaded the menu bar app could expand to indicate that it is running? Without knowing it's a menu bar app, I did not realize I had it installed until you mentioned it in here.

**Comment by ChangJoo-Park** [comment]
OK I'll do this next release :)
