### ISSUE TITLE
Github repo says it has no releases but has 107 of them. 

### ISSUE THREAD

**Issue by levibostian** [ChangJoo-Park/gitrelease-app#2]
Tried adding `realm/realm-java` github project to gitrelease. The app found the repo, but when I hit Save, it said that there were no releases for the project. This resulted in gitrelease-app not adding the lib. 

There are actually [107 releases](https://github.com/realm/realm-java/releases) for the repo.

**Comment by ChangJoo-Park** [comment]
This is a known issue. It happens because `gitrelease` depend on the **github api**. I'm looking for another way for find releases.

Thank you @levibostian !
